SELECT SCHOOLS.NAME_OF_SCHOOL, CENSUS.COMMUNITY_AREA_NAME, SCHOOLS.AVERAGE_STUDENT_ATTENDANCE
FROM CHICAGO_PUBLIC_SCHOOLS AS SCHOOLS LEFT OUTER JOIN CENSUS_DATA AS CENSUS
ON SCHOOLS.COMMUNITY_AREA_NUMBER = CENSUS.COMMUNITY_AREA_NUMBER
WHERE CENSUS.HARDSHIP_INDEX = 98