SELECT CRIME.CASE_NUMBER, CRIME.PRIMARY_TYPE, CENSUS.COMMUNITY_AREA_NAME
FROM CHICAGO_CRIME_DATA AS CRIME LEFT OUTER JOIN CENSUS_DATA AS CENSUS 
ON CRIME.COMMUNITY_AREA_NUMBER = CENSUS.COMMUNITY_AREA_NUMBER
WHERE LOCATION_DESCRIPTION LIKE '%SCHOOL%'